import os

# Названия таблиц
ADVISOR_TABLE = os.getenv('ADVISOR_TABLE')
ADVISOR_USER_BDAY_TABLE = os.getenv('ADVISOR_USER_BDAY_TABLE')
ADVISOR_EVENTS_TABLE = os.getenv('ADVISOR_EVENTS_TABLE')

CONGRATULATION_CODES = ['BIRTHDAY', 'COMPANY_ANNIVERSARY', 'CLIENT_ANNIVERSARY', 'INDUSTRY_DAY',]
BLOCKING_REASONS = ['CASH', 'IE', 'FL', 'NDS', 'OKVED', 'BAD_CONTR', 'NALOG', 'HIDDEN',]

PRODUCT_OFFERS = ['SALARY_PROJECT', 'BUSINESS_CARDS', 'CREDIT', 'DEPOSIT', 'ACQUIRING', 'GUARANTEE', 'NSO', 'VED',
                  'SMS', 'ENCASHMENT', 'MOBILE_BANKING',]
TARIFFS = ['BIG_PLAN', 'CTS', 'FIRTS_STEP', 'START', 'FLY',]
